name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests for adapters

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.16"

    - name: Setup poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.3.1"

    - name: Install dependencies and needed compilers
      working-directory: odd-collector
      run: |
        sudo apt-get update && sudo apt-get install -y -q build-essential \
        python3-dev libpq-dev curl librdkafka-dev unixodbc \
        unixodbc-dev openssl libsasl2-dev
        poetry install

    # for now, only tests for PostgreSQL and Snowflake adapters are being invoked,
    # others need to be checked and updated for future use
    - name: Run tests
      working-directory: odd-collector
      run: |
        poetry run pytest tests/integration/test_postgres.py -v
        poetry run pytest tests/adapters/snowflake -v
